<a href="https://colab.research.google.com/github/Nermeen-Moussa/ML-DL-Reference-Guide/blob/machine-learning/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**RandomForestClassifier=>There is a lot of decision trees (majority voties) to the final classifer**

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report

Mounted at /content/drive

In [2]:
df=pd.read_csv('/content/drive/MyDrive/500hits.csv',encoding='latin1')
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [5]:
X=df.iloc[:,0:13]
y=df.iloc[:,13]

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)
rf.score(X_test,y_test)

0.8817204301075269

In [8]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.94      0.91        62
           1       0.86      0.77      0.81        31

    accuracy                           0.88        93
   macro avg       0.87      0.85      0.86        93
weighted avg       0.88      0.88      0.88        93

In [10]:
features=pd.DataFrame({'feature':X.columns,'importance':rf.feature_importances_})
features.head()

  feature  importance
0     YRS    0.030215
1       G    0.056626
2      AB    0.082737
3       R    0.142802
4       H    0.119960

In [11]:
rf2=RandomForestClassifier(n_estimators=1000,random_state=42,criterion='entropy',min_samples_split=10,max_depth=14)
rf2.fit(X_train,y_train)
y_pred2=rf2.predict(X_test)
rf2.score(X_test,y_test)

0.8817204301075269

In [12]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.89      0.94      0.91        62
           1       0.86      0.77      0.81        31

    accuracy                           0.88        93
   macro avg       0.87      0.85      0.86        93
weighted avg       0.88      0.88      0.88        93